Dns Forwarder v.1.0: DFNS::Model Class Reference
DFNS::Model Class Reference
#include <Model.h>
Public Member Functions
Model ()
~Model ()
string getDfSrvIp ()
int getDfSrvPort ()
string getDnsSrvIp ()
int getDnsSrvPort ()
bool init (Log::LogLvl logLvl, string upstreamDnsSrvIp, int upstreamDnsSrvPort)
bool isTransIdInMap (int transId)
void addEndPoint (int transId, string &ip, int port)
EndPoint getEndPoint (int transId)
Static Public Attributes
static const char * DF_SRV_IP = "127.0.0.1"
static const int DF_SRV_PORT = 1917
Private Attributes
string dfSrvIp
int dfSrvPort
string dnsSrvIp
int dnsSrvPort
map< int, EndPoint * > cliTransIdMap
Detailed Description
Class stores IP-port pair.
Definition at line 25 of file Model.h.
Constructor & Destructor Documentation
Model()
DFNS::Model::Model ()
Default constructor.
Definition at line 17 of file Model.cpp.
~Model()
DFNS::Model::~Model ()
Destructor that deallocates an object.
Definition at line 25 of file Model.cpp.
References cliTransIdMap.
Member Function Documentation
addEndPoint()
void DFNS::Model::addEndPoint (int transId, string & ip, int port)
Add ip-port end point to the map.
Parameters
transId Transaction ID integer number.
ip Reference to string containing IP number in dot notation.
port Port number, integer value.
Returns
void
Definition at line 67 of file Model.cpp.
References cliTransIdMap, DFNS::Log::MSG_TYPE_ERR, and DFNS::Log::printMsg().
Referenced by DFNS::Controller::run().
getDfSrvIp()
string DFNS::Model::getDfSrvIp ()
Getter for dfSrvIp member.
Returns
string IP address in dot-notation.
Definition at line 34 of file Model.cpp.
References dfSrvIp.
Referenced by DFNS::Controller::init().
getDfSrvPort()
int DFNS::Model::getDfSrvPort ()
Getter for dfSrvPort member.
Returns
int Port number.
Definition at line 38 of file Model.cpp.
References dfSrvPort.
Referenced by DFNS::Controller::init().
getDnsSrvIp()
string DFNS::Model::getDnsSrvIp ()
Getter for dnsSrvIp member.
Returns
string IP address in dot-notation.
Definition at line 42 of file Model.cpp.
References dnsSrvIp.
Referenced by DFNS::Controller::run().
getDnsSrvPort()
int DFNS::Model::getDnsSrvPort ()
Getter for dnsSrvPort member.
Returns
int Port number.
Definition at line 46 of file Model.cpp.
References dnsSrvPort.
Referenced by DFNS::Controller::run().
getEndPoint()
EndPoint DFNS::Model::getEndPoint (int transId)
Find and return EndPoint using transId number.
Parameters
transId Transaction ID integer number.
Returns
EndPoint object. If not found, the object contains empty IP string and zero port.
Definition at line 76 of file Model.cpp.
References cliTransIdMap.
Referenced by DFNS::Controller::run().
init()
bool DFNS::Model::init (Log::LogLvl logLvl, string upstreamDnsSrvIp, int upstreamDnsSrvPort)
Sets log level. Allocates and initializes controller.
Returns
bool True, if success. False, if error occurs.
Definition at line 51 of file Model.cpp.
References dnsSrvIp, dnsSrvPort, and DFNS::Log::logLvl.
Referenced by DFNS::Controller::init().
isTransIdInMap()
bool DFNS::Model::isTransIdInMap (int transId)
Check if transId is in the map.
Parameters
transId Transaction ID integer number.
Returns
true, if found, false, otherwise.
Definition at line 63 of file Model.cpp.
References cliTransIdMap.
Referenced by DFNS::Controller::run().
Member Data Documentation
cliTransIdMap
map<int, EndPoint*> DFNS::Model::cliTransIdMap private
Map of clients' end-points(IP+port). Key - transaction ID. Value - EndPoint object.
Definition at line 142 of file Model.h.
Referenced by addEndPoint(), getEndPoint(), isTransIdInMap(), and ~Model().
DF_SRV_IP
const char * DFNS::Model::DF_SRV_IP = "127.0.0.1" static
Server IP of listen endpoint for DNS forwarder.
Definition at line 33 of file Model.h.
DF_SRV_PORT
const int DFNS::Model::DF_SRV_PORT = 1917 static
Server port of listen endpoint for DNS forwarder.
Definition at line 38 of file Model.h.
dfSrvIp
string DFNS::Model::dfSrvIp private
Server IP of DNS Forwarder, listen endpoint is hardcoded to 127.0.0.1:1917.
Definition at line 122 of file Model.h.
Referenced by getDfSrvIp().
dfSrvPort
int DFNS::Model::dfSrvPort private
Server port of DNS Forwarder, listen endpoint is hardcoded to 127.0.0.1:1917.
Definition at line 127 of file Model.h.
Referenced by getDfSrvPort().
dnsSrvIp
string DFNS::Model::dnsSrvIp private
IP of upstream DNS server, from command line arguments.
Definition at line 132 of file Model.h.
Referenced by getDnsSrvIp(), and init().
dnsSrvPort
int DFNS::Model::dnsSrvPort private
Port of upstream DNS server, from command line arguments.
Definition at line 137 of file Model.h.
Referenced by getDnsSrvPort(), and init().
The documentation for this class was generated from the following files:
/media/tuner/HD-Data/2019/Data/work-space/local/Eclipse/C++/dns_forwarder/include/Model.h
/media/tuner/HD-Data/2019/Data/work-space/local/Eclipse/C++/dns_forwarder/src/model/Model.cpp