Dns Forwarder v.1.0: DFNS::DnsForwarder Class Reference
DFNS::DnsForwarder Class Reference
#include <DnsForwarder.h>
Public Member Functions
DnsForwarder ()
~DnsForwarder ()
bool init (Log::LogLvl logLvl, string upstreamDnsSrvIp, int upstreamDnsSrvPort)
bool run ()
Private Attributes
Controller * controller
Detailed Description
Class declares functionality of DNS forwarder.
Definition at line 23 of file DnsForwarder.h.
Constructor & Destructor Documentation
DnsForwarder()
DFNS::DnsForwarder::DnsForwarder ()
Default constructor.
Definition at line 16 of file DnsForwarder.cpp.
~DnsForwarder()
DFNS::DnsForwarder::~DnsForwarder ()
Destructor deallocates controller.
Definition at line 20 of file DnsForwarder.cpp.
References controller.
Member Function Documentation
init()
bool DFNS::DnsForwarder::init (Log::LogLvl logLvl, string upstreamDnsSrvIp, int upstreamDnsSrvPort)
Set log level. Allocate and initialize controller.
Parameters
logLvl Log level of type Log::LogLvl.
upstreamDnsSrvIp IP address of the upstream DNS server.
upstreamDnsSrvPort Port number of the upstream DNS server.
Returns
bool True, if success. False, if error occurs.
Definition at line 25 of file DnsForwarder.cpp.
References controller, DFNS::Controller::init(), DFNS::Log::MSG_TYPE_ERR, and DFNS::Log::printMsg().
Referenced by main().
run()
bool DFNS::DnsForwarder::run ()
Run controller.
Returns
bool True, if success. False, if error occurs.
Definition at line 42 of file DnsForwarder.cpp.
References controller, DFNS::Log::MSG_TYPE_ERR, DFNS::Log::printMsg(), and DFNS::Controller::run().
Referenced by main().
Member Data Documentation
controller
Controller* DFNS::DnsForwarder::controller private
Controller that defines the logic of the application.
Definition at line 63 of file DnsForwarder.h.
Referenced by init(), run(), and ~DnsForwarder().
The documentation for this class was generated from the following files:
/media/tuner/HD-Data/2019/Data/work-space/local/Eclipse/C++/dns_forwarder/include/DnsForwarder.h
/media/tuner/HD-Data/2019/Data/work-space/local/Eclipse/C++/dns_forwarder/src/dnsForwarder/DnsForwarder.cpp