Dns Forwarder v.1.0: DFNS::Log Class Reference
DFNS::Log Class Reference
#include <Log.h>
Public Types
enum MsgType { MSG_TYPE_INF, MSG_TYPE_DBG, MSG_TYPE_WRN, MSG_TYPE_ERR }
enum LogLvl { LOG_LVL_NORMAL, LOG_LVL_VERBOSE }
Static Public Member Functions
static void printMsg (MsgType msgType, const string &msg, const string &funcName=string(__builtin_FUNCTION()), const string &fileName=string(__builtin_FILE()))
static void printMsg (MsgType msgType, const char *msg, const string &funcName=string(__builtin_FUNCTION()), const string &fileName=string(__builtin_FILE()))
static void printVars (MsgType msgType, string formatMsg,...)
Static Public Attributes
static int logLvl = Log::LOG_LVL_NORMAL
Static Private Member Functions
static void printMsg (MsgType msgType, const string &msg, bool printMsgType, bool printTimeStamp, bool printFuncName, const string &funcName=string(__builtin_FUNCTION()), const string &fileName=string(__builtin_FILE()))
static void printMsg (MsgType msgType, const char *msg, bool printMsgType, bool printTimeStamp, bool printFuncName, const string &funcName=string(__builtin_FUNCTION()), const string &fileName=string(__builtin_FILE()))
static string getTimeStamp ()
static string getFuncName (const string &funcName)
static string getClassName (const string &fileName)
Detailed Description
Class declares logging mechanism for the application.
Definition at line 22 of file Log.h.
Member Enumeration Documentation
LogLvl
enum DFNS::Log::LogLvl
Enum type of log's level.
Enumerator
LOG_LVL_NORMAL
LOG_LVL_VERBOSE
Definition at line 39 of file Log.h.
MsgType
enum DFNS::Log::MsgType
Enum type of message.
Enumerator
MSG_TYPE_INF
MSG_TYPE_DBG
MSG_TYPE_WRN
MSG_TYPE_ERR
Definition at line 29 of file Log.h.
Member Function Documentation
getClassName()
string DFNS::Log::getClassName (const string & fileName) static private
Static method that returns the name of class.
Returns
string Returns the name of class.
Definition at line 145 of file Log.cpp.
Referenced by printMsg().
getFuncName()
string DFNS::Log::getFuncName (const string & funcName) static private
Static method that returns the name of function.
Returns
string Returns the name of function.
Definition at line 140 of file Log.cpp.
Referenced by printMsg().
getTimeStamp()
string DFNS::Log::getTimeStamp () static private
Static method that returns the current time-stamp.
Returns
string Returns time-stamp using the format "yyyy.mm.dd hh:mm:ss".
Definition at line 130 of file Log.cpp.
Referenced by printMsg().
printMsg() [1/4]
void DFNS::Log::printMsg (MsgType msgType, const string & msg, const string & funcName = string(__builtin_FUNCTION()), const string & fileName = string(__builtin_FILE())) static
Static method for printing various types of messages.
Parameters
msgType Type of message to be printed.
msg Reference to string containing message.
funcName Reference to function name with default value string(__builtin_FUNCTION()).
fileName Reference to file name with default value string(__builtin_FILE()).
Returns
void
Definition at line 23 of file Log.cpp.
References LOG_LVL_NORMAL.
Referenced by DFNS::Model::addEndPoint(), DFNS::DnsForwarder::init(), DFNS::Controller::init(), DFNS::CmdLineArgs::parse(), printMsg(), printVars(), DFNS::NetComponent::recvFromCli(), DFNS::NetComponent::recvFromSrv(), DFNS::DnsForwarder::run(), DFNS::Controller::run(), DFNS::NetComponent::sendToCli(), and DFNS::NetComponent::sendToSrv().
printMsg() [2/4]
void DFNS::Log::printMsg (MsgType msgType, const char * msg, const string & funcName = string(__builtin_FUNCTION()), const string & fileName = string(__builtin_FILE())) static
Static method for printing various types of messages.
Parameters
msgType Type of message to be printed.
msg Pointer to char buffer containing message.
funcName Reference to function name with default value string(__builtin_FUNCTION()).
fileName Reference to file name with default value string(__builtin_FILE()).
Returns
void
Definition at line 35 of file Log.cpp.
References LOG_LVL_NORMAL, and printMsg().
printMsg() [3/4]
void DFNS::Log::printMsg (MsgType msgType, const string & msg, bool printMsgType, bool printTimeStamp, bool printFuncName, const string & funcName = string(__builtin_FUNCTION()), const string & fileName = string(__builtin_FILE())) static private
Static method for printing various types of messages.
Parameters
msgType Type of message to be printed.
msg Reference to string containing message.
printMsgType Boolean flag for printing message type.
printTimeStamp Boolean flag for printing time stamp.
printFuncName Boolean flag for printing function's name.
funcName Reference to function name with default value string(__builtin_FUNCTION()).
fileName Reference to file name with default value string(__builtin_FILE()).
Returns
void
Definition at line 60 of file Log.cpp.
References DFNS::IOColor::FG_CODE_BRIGHT_CYAN, DFNS::IOColor::FG_CODE_BRIGHT_GREEN, DFNS::IOColor::FG_CODE_BRIGHT_MAGENTA, DFNS::IOColor::FG_CODE_BRIGHT_RED, DFNS::IOColor::FG_CODE_RESET_NORMAL, getClassName(), getFuncName(), getTimeStamp(), MSG_TYPE_DBG, MSG_TYPE_ERR, MSG_TYPE_INF, MSG_TYPE_WRN, and printVars().
printMsg() [4/4]
void DFNS::Log::printMsg (MsgType msgType, const char * msg, bool printMsgType, bool printTimeStamp, bool printFuncName, const string & funcName = string(__builtin_FUNCTION()), const string & fileName = string(__builtin_FILE())) static private
Static method for printing various types of messages.
Parameters
msgType Type of message to be printed.
msg Pointer to char buffer containing message.
printMsgType Boolean flag for printing message type.
printTimeStamp Boolean flag for printing time stamp.
printFuncName Boolean flag for printing function's name.
funcName Reference to function name with default value string(__builtin_FUNCTION()).
fileName Reference to file name with default value string(__builtin_FILE()).
Returns
void
Definition at line 118 of file Log.cpp.
References printMsg().
printVars()
void DFNS::Log::printVars (MsgType msgType, string formatMsg, ...) static
Static method for printing various types of messages.
Parameters
msgType Type of message to be printed.
formatMsg Format string that defines formatted output like in printf().
... Variable number of arguments.
Returns
void
Definition at line 46 of file Log.cpp.
References printMsg().
Referenced by DFNS::NetComponent::init(), printMsg(), DFNS::Controller::run(), and DFNS::NetComponent::sendTo().
Member Data Documentation
logLvl
int DFNS::Log::logLvl = Log::LOG_LVL_NORMAL static
Static member containing log's level.
Definition at line 48 of file Log.h.
Referenced by DFNS::Model::init().
The documentation for this class was generated from the following files:
/media/tuner/HD-Data/2019/Data/work-space/local/Eclipse/C++/dns_forwarder/include/Log.h
/media/tuner/HD-Data/2019/Data/work-space/local/Eclipse/C++/dns_forwarder/src/log/Log.cpp