Dns Forwarder v.1.0: DFNS::NetComponent Class Reference
DFNS::NetComponent Class Reference
#include <NetComponent.h>
Public Member Functions
NetComponent ()
~NetComponent ()
bool init (string dfSrvIp, int dfSrvPort)
bool recvFromCli (string &srcIp, int &srcPort, vector< char > &msgBuf, int &numOfRcvdBytes)
bool recvFromSrv (string &srcIp, int &srcPort, vector< char > &msgBuf, int &numOfRcvdBytes)
bool sendToSrv (const string &destIp, const int destPort, const vector< char > &msgBuf, int &numOfSentBytes)
bool sendToCli (const string &destIp, const int destPort, const vector< char > &msgBuf, int &numOfSentBytes)
Private Member Functions
bool recvFrom (int socket, string &srcIp, int &srcPort, vector< char > &msgBuf, int &numOfRcvdBytes)
bool sendTo (int socket, const string &destIp, const int destPort, const vector< char > &msgBuf, int &numOfSentBytes)
Private Attributes
int socketForwarderAndCli
int socketForwarderAndSrv
Detailed Description
Class declares network functionality for DNS forwarder.
Definition at line 27 of file NetComponent.h.
Constructor & Destructor Documentation
NetComponent()
DFNS::NetComponent::NetComponent ()
Default constructor.
Definition at line 18 of file NetComponent.cpp.
~NetComponent()
DFNS::NetComponent::~NetComponent ()
Destructor.
Definition at line 23 of file NetComponent.cpp.
Member Function Documentation
init()
bool DFNS::NetComponent::init (string dfSrvIp, int dfSrvPort)
Initialize NetComponent of DNS forwarder.
Create socket for DNS forwarder - client communication.
Create socket for DNS forwarder - server communication.
Bind socket for DNS forwarder - client communication.
Parameters
dfSrvIp IP address of DNS forwarder's server.
dfSrvPort Port number of DNS forwarder's server.
Returns
bool True, if success. False, if error occurs.
Definition at line 27 of file NetComponent.cpp.
References DFNS::Log::MSG_TYPE_ERR, DFNS::Log::printVars(), socketForwarderAndCli, and socketForwarderAndSrv.
Referenced by DFNS::Controller::init().
recvFrom()
bool DFNS::NetComponent::recvFrom (int socket, string & srcIp, int & srcPort, vector< char > & msgBuf, int & numOfRcvdBytes) private
Receive a message from a socket.
Receive a message from a socket, store it in msgBuf. Return srcIp and srcPort. Return numOfRcvdBytes.
Parameters
socket The file descriptor of the socket.
srcIp Reference to the string containing source IP address using string dot notation.
srcPort Reference to destination port, integer value.
msgBuf Reference to vector's buffer containing a message.
numOfRcvdBytes Reference to the parameter containing the number of received bytes.
Returns
bool True, if success. False, if error occurs.
Definition at line 125 of file NetComponent.cpp.
Referenced by recvFromCli(), and recvFromSrv().
recvFromCli()
bool DFNS::NetComponent::recvFromCli (string & srcIp, int & srcPort, vector< char > & msgBuf, int & numOfRcvdBytes)
Receive a message from a client.
Receive a message from a client, store it in msgBuf. Return srcIp and srcPort. Return numOfRcvdBytes.
Parameters
srcIp Reference to the string containing source IP address using string dot notation.
srcPort Reference to destination port, integer value.
msgBuf Reference to vector's buffer containing a message.
numOfRcvdBytes Reference to the parameter containing the number of received bytes.
Returns
bool True, if success. False, if error occurs.
Definition at line 68 of file NetComponent.cpp.
References DFNS::Log::MSG_TYPE_ERR, DFNS::Log::printMsg(), recvFrom(), and socketForwarderAndCli.
Referenced by DFNS::Controller::run().
recvFromSrv()
bool DFNS::NetComponent::recvFromSrv (string & srcIp, int & srcPort, vector< char > & msgBuf, int & numOfRcvdBytes)
Receive a message from a server.
Receive a message from a server, store it in msgBuf. Return srcIp and srcPort. Return numOfRcvdBytes.
Parameters
srcIp Reference to the string containing source IP address using string dot notation.
srcPort Reference to destination port, integer value.
msgBuf Reference to vector's buffer containing a message.
numOfRcvdBytes Reference to the parameter containing the number of received bytes.
Returns
bool True, if success. False, if error occurs.
Definition at line 81 of file NetComponent.cpp.
References DFNS::Log::MSG_TYPE_ERR, DFNS::Log::printMsg(), recvFrom(), and socketForwarderAndSrv.
Referenced by DFNS::Controller::run().
sendTo()
bool DFNS::NetComponent::sendTo (int socket, const string & destIp, const int destPort, const vector< char > & msgBuf, int & numOfSentBytes) private
Send a message on a socket.
Send msgBuf's payload using destIp and destPort over socket. Return number of sent bytes in numOfSentBytes.
Parameters
socket The file descriptor of the sending socket.
destIp Reference to the string containing destination IP address using string dot notation.
destPort Destination port, integer value.
msgBuf Reference to vector's buffer containing a message.
numOfSentBytes Reference to the parameter containing the number of sent bytes.
Returns
bool True, if success. False, if error occurs.
Definition at line 162 of file NetComponent.cpp.
References DFNS::Log::MSG_TYPE_ERR, and DFNS::Log::printVars().
Referenced by sendToCli(), and sendToSrv().
sendToCli()
bool DFNS::NetComponent::sendToCli (const string & destIp, const int destPort, const vector< char > & msgBuf, int & numOfSentBytes)
Send a message to a client.
Send msgBuf's payload using destIp and destPort to a client. Return number of sent bytes in numOfSentBytes.
Parameters
destIp Reference to the string containing destination IP address using string dot notation.
destPort Destination port, integer value.
msgBuf Reference to vector's buffer containing a message.
numOfSentBytes Reference to the parameter containing the number of sent bytes.
Returns
bool True, if success. False, if error occurs.
Definition at line 109 of file NetComponent.cpp.
References DFNS::Log::MSG_TYPE_ERR, DFNS::Log::printMsg(), sendTo(), and socketForwarderAndCli.
Referenced by DFNS::Controller::run().
sendToSrv()
bool DFNS::NetComponent::sendToSrv (const string & destIp, const int destPort, const vector< char > & msgBuf, int & numOfSentBytes)
Send a message to a server.
Send msgBuf's payload using destIp and destPort to a server. Return number of sent bytes in numOfSentBytes.
Parameters
destIp Reference to the string containing destination IP address using string dot notation.
destPort Destination port, integer value.
msgBuf Reference to vector's buffer containing a message.
numOfSentBytes Reference to the parameter containing the number of sent bytes.
Returns
bool True, if success. False, if error occurs.
Definition at line 94 of file NetComponent.cpp.
References DFNS::Log::MSG_TYPE_ERR, DFNS::Log::printMsg(), sendTo(), and socketForwarderAndSrv.
Referenced by DFNS::Controller::run().
Member Data Documentation
socketForwarderAndCli
int DFNS::NetComponent::socketForwarderAndCli private
The file descriptor of the socket with binding for communication between DNS forwarder and client.
Definition at line 140 of file NetComponent.h.
Referenced by init(), recvFromCli(), and sendToCli().
socketForwarderAndSrv
int DFNS::NetComponent::socketForwarderAndSrv private
The file descriptor of the socket with no binding for communication between DNS forwarder and server.
Definition at line 146 of file NetComponent.h.
Referenced by init(), recvFromSrv(), and sendToSrv().
The documentation for this class was generated from the following files:
/media/tuner/HD-Data/2019/Data/work-space/local/Eclipse/C++/dns_forwarder/include/NetComponent.h
/media/tuner/HD-Data/2019/Data/work-space/local/Eclipse/C++/dns_forwarder/src/net/NetComponent.cpp