Dns Forwarder v.1.0: DFNS::Controller Class Reference
DFNS::Controller Class Reference
#include <Controller.h>
Public Member Functions
Controller ()
~Controller ()
bool init (Log::LogLvl logLvl, string upstreamDnsSrvIp, int upstreamDnsSrvPort)
bool run ()
Private Attributes
Model * model
NetComponent * netComponent
Detailed Description
Class declares logic of DNS forwarder.
Definition at line 28 of file Controller.h.
Constructor & Destructor Documentation
Controller()
DFNS::Controller::Controller ()
Default constructor.
Definition at line 18 of file Controller.cpp.
~Controller()
DFNS::Controller::~Controller ()
Destructor that deallocates net component and all end points in the map.
Definition at line 22 of file Controller.cpp.
References model, and netComponent.
Member Function Documentation
init()
bool DFNS::Controller::init (Log::LogLvl logLvl, string upstreamDnsSrvIp, int upstreamDnsSrvPort)
Allocate and initialize net component.
Parameters
logLvl Log level of type Log::LogLvl.
upstreamDnsSrvIp IP address of the upstream DNS server.
upstreamDnsSrvPort Port number of the upstream DNS server.
Returns
bool True, if success. False, if error occurs.
Definition at line 28 of file Controller.cpp.
References DFNS::Model::getDfSrvIp(), DFNS::Model::getDfSrvPort(), DFNS::NetComponent::init(), DFNS::Model::init(), model, DFNS::Log::MSG_TYPE_ERR, netComponent, and DFNS::Log::printMsg().
Referenced by DFNS::DnsForwarder::init().
run()
bool DFNS::Controller::run ()
Run controller of DNS forwarder.
Receives request from client.
Forwards request to DNS server.
Receives reply from DNS server.
Forwards reply to DNS client.
Returns
bool True, if success. False, if error occurs.
Definition at line 59 of file Controller.cpp.
References DFNS::Model::addEndPoint(), DFNS::Model::getDnsSrvIp(), DFNS::Model::getDnsSrvPort(), DFNS::Model::getEndPoint(), DFNS::EndPoint::getIp(), DFNS::EndPoint::getPort(), DFNS::DnsHeader::getTransId(), DFNS::Model::isTransIdInMap(), model, DFNS::Log::MSG_TYPE_DBG, DFNS::Log::MSG_TYPE_ERR, DFNS::Log::MSG_TYPE_INF, DFNS::Log::MSG_TYPE_WRN, netComponent, DFNS::Log::printMsg(), DFNS::Log::printVars(), DFNS::NetComponent::recvFromCli(), DFNS::NetComponent::recvFromSrv(), DFNS::NetComponent::sendToCli(), and DFNS::NetComponent::sendToSrv().
Referenced by DFNS::DnsForwarder::run().
Member Data Documentation
model
Model* DFNS::Controller::model private
Pointer to model that stores application's data.
Definition at line 75 of file Controller.h.
Referenced by init(), run(), and ~Controller().
netComponent
NetComponent* DFNS::Controller::netComponent private
Pointer to NetComponent's object. It is responsible for net communication with clients and server.
Definition at line 81 of file Controller.h.
Referenced by init(), run(), and ~Controller().
The documentation for this class was generated from the following files:
/media/tuner/HD-Data/2019/Data/work-space/local/Eclipse/C++/dns_forwarder/include/Controller.h
/media/tuner/HD-Data/2019/Data/work-space/local/Eclipse/C++/dns_forwarder/src/controller/Controller.cpp