Dns Forwarder v.1.0: DFNS::CmdLineArgs Class Reference
DFNS::CmdLineArgs Class Reference
#include <CmdLineArgs.h>
Public Member Functions
CmdLineArgs ()
~CmdLineArgs ()
Log::LogLvl getLogLvl ()
string getUpstreamDnsSrvIp ()
int getUpstreamDnsPort ()
void parse (int argc, char *argv[])
Private Attributes
string hlpMsg
Log::LogLvl logLvl
string upstreamDnsSrvIp
int upstreamDnsPort
Detailed Description
Class parses command-line arguments: help message, log's level, IP and port of upstream DNS server.
Definition at line 24 of file CmdLineArgs.h.
Constructor & Destructor Documentation
CmdLineArgs()
DFNS::CmdLineArgs::CmdLineArgs ()
Constructor that creates log's help message, initializes log's level, DNS server's IP and port.
Definition at line 23 of file CmdLineArgs.cpp.
References DFNS::IOColor::FG_CODE_BRIGHT_BLUE, DFNS::IOColor::FG_CODE_BRIGHT_YELLOW, DFNS::IOColor::FG_CODE_RESET_NORMAL, and hlpMsg.
~CmdLineArgs()
DFNS::CmdLineArgs::~CmdLineArgs ()
Destructor deallocates an object.
Definition at line 57 of file CmdLineArgs.cpp.
Member Function Documentation
getLogLvl()
Log::LogLvl DFNS::CmdLineArgs::getLogLvl ()
Getter method for logLvl member.
Returns
Log::LogLvl Log level of the application.
Definition at line 61 of file CmdLineArgs.cpp.
References logLvl.
Referenced by main().
getUpstreamDnsPort()
int DFNS::CmdLineArgs::getUpstreamDnsPort ()
Getter method for upstreamDnsPort member.
Returns
int Port number of upstream DNS server.
Definition at line 69 of file CmdLineArgs.cpp.
References upstreamDnsPort.
Referenced by main().
getUpstreamDnsSrvIp()
string DFNS::CmdLineArgs::getUpstreamDnsSrvIp ()
Getter method for upstreamDnsSrvIp member.
Returns
string IP address of upstream DNS server using dot-notation.
Definition at line 65 of file CmdLineArgs.cpp.
References upstreamDnsSrvIp.
Referenced by main().
parse()
void DFNS::CmdLineArgs::parse (int argc, char * argv[])
Parse command-line arguments.
Parameters
argc Number of command-line arguments.
argv Array of command-line arguments.
Returns
void
Definition at line 74 of file CmdLineArgs.cpp.
References DFNS::APP_EXIT_FAILURE, DFNS::APP_EXIT_SUCCESS, hlpMsg, DFNS::Log::LOG_LVL_NORMAL, DFNS::Log::LOG_LVL_VERBOSE, logLvl, DFNS::Log::MSG_TYPE_ERR, DFNS::Log::MSG_TYPE_INF, DFNS::Log::printMsg(), upstreamDnsPort, and upstreamDnsSrvIp.
Referenced by main().
Member Data Documentation
hlpMsg
string DFNS::CmdLineArgs::hlpMsg private
Help message for application's executable.
Definition at line 78 of file CmdLineArgs.h.
Referenced by CmdLineArgs(), and parse().
logLvl
Log::LogLvl DFNS::CmdLineArgs::logLvl private
Verbose or non-verbose log's level.
Definition at line 83 of file CmdLineArgs.h.
Referenced by getLogLvl(), and parse().
upstreamDnsPort
int DFNS::CmdLineArgs::upstreamDnsPort private
Port number of upstream DNS server.
Definition at line 93 of file CmdLineArgs.h.
Referenced by getUpstreamDnsPort(), and parse().
upstreamDnsSrvIp
string DFNS::CmdLineArgs::upstreamDnsSrvIp private
IP address of upstream DNS server.
Definition at line 88 of file CmdLineArgs.h.
Referenced by getUpstreamDnsSrvIp(), and parse().
The documentation for this class was generated from the following files:
/media/tuner/HD-Data/2019/Data/work-space/local/Eclipse/C++/dns_forwarder/include/CmdLineArgs.h
/media/tuner/HD-Data/2019/Data/work-space/local/Eclipse/C++/dns_forwarder/src/cmdLineArgs/CmdLineArgs.cpp